### ISSUE TITLE
problem: [/addcoin] client side validation on add currency page is complicated and confusing

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#617] opened 2018-03-18 04:02 UTC
Problem: client side validation on the add currency page is confusing. 

Possible solution: from the UI perspective we should probably use jquery or whatever to highlight invalid fields onBlur.

On the server side and client side, it's probably best to use simplSchema and validate based on that so that we don't repeat validation logic. This could be executed on the client side and data only sent to the server for validation if it passes on the client.

ping @janat08 @anbud @AshHimself

**Comment by janat08** [comment] 2018-03-18 07:25
https://github.com/meteor/validated-method#validation-and-throwstubexceptions
or wtv.

**Comment by AshHimself** [comment] 2018-03-18 07:32
@janat08 I believe we are more talking about UX level on top of what you are talking about. e.g. highlight the culprit fields and provide a UX friendly error stating what they need to do to resolve their issue.

**Comment by gazhayes** [comment] 2018-03-18 08:03
@janat08 and @AshHimself I think you're both right. Validated method is a good solution for both client and server side validation. Jquery is a good solution for client side DOM manipulation to show the user which specific fields failed validation.

Is this making sense to both of you?

**Comment by AshHimself** [comment] 2018-03-18 08:50
Bingo.

**Comment by gazhayes** [comment] 2018-03-18 08:55
I need to actually verify that those forms right though from a blockchain project standpoint, I'll probably be logging an issue in the next few days with updates to the form. Solving that will be a dependency for solving this one (otherwise work will have to be repeated). 

We do need to decide on the simplest solution however (the least amount of code required to solve this).

Has anyone actually used simplSchema and validated-method in a project before? ping @anbud

**Comment by AshHimself** [comment] 2018-03-18 09:58
I’ve used both before with auto form.

**Comment by gazhayes** [comment] 2018-03-18 10:00
I think autoform uses allow/deny rules instead of using methods, right?

**Comment by janat08** [comment] 2018-03-18 11:40
I don't know what jquery lib offers, but I imagine there should be some error message with which you could invalidate ui fields in MDG lib.

**Comment by AshHimself** [comment] 2018-03-18 11:45
It does, I don’t suggest we use it either as i had major issues with it on
Meteor 1.6. We can use simpleschema though without it no issues. I suggest
we get it up and running just on one page to start with. e.g. posting
comments or something similar complexity.

**Comment by gazhayes** [comment] 2018-03-18 11:58
> I suggest we get it up and running just on one page to start with. e.g. posting comments or something similar complexity.

It's not really a problem on those pages, there's only one field per form and the errors are working properly with no performance issues etc as far as I can tell.

It's worth it for the add currency page because it's actually not working properly at the moment so something has to be done anyway. It's also one aspect that will very likely change very often as we hit the firehose of reality and discover what's missing, so having validation etc done in a robust way is very useful.

**Comment by janat08** [comment] 2018-03-18 14:44
I think he wants a test run.

**Comment by gazhayes** [comment] 2018-03-18 14:59
No need for that. We can test it for real.

**Comment by janat08** [comment] 2018-03-18 15:21
to draw comparison between potential solutions?

**Comment by anbud** [comment] 2018-03-18 17:37
I've been using simplschema with validated method before, it's not too complex, and it's quite good for this issue I believe. About UI validations, jquery to the rescue. We can probably also use meteor's built-in reactivity to, for example, highlight invalid fields and stuff.

**Comment by AshHimself** [comment] 2018-04-10 04:49
Do we still have an unmet dependency on this ticket? Are we not using validated-method now to use for client side validation on this page? @gazhayes - This page needs a lot of work on the UX whilst adding tickets and validated-method could assist with that giving inline form errors I believe.

**Comment by janat08** [comment] 2018-04-10 04:51
#641 is the dependency.

**Comment by AshHimself** [comment] 2018-04-10 04:53
In what way? Is #641 not done. I guess I am not following the issue correctly then.

**Comment by janat08** [comment] 2018-04-10 05:16
Sorry, #624

**Comment by gazhayes** [comment] 2018-04-10 05:29
@AshHimself  @janat08 I just freed this up. The dependency is close enough, just be aware that some fields may change.

**Comment by AshHimself** [comment] 2018-04-10 05:31
@janat08 you ok for me to take this as I have no other tickets on my plate right now.

**Comment by janat08** [comment] 2018-04-10 05:33
ye, I don't do jquery.

**Comment by gazhayes** [comment] 2018-04-10 05:33
It's nice to be polite, but there's no need for consensus. @AshHimself are you planning on using validated-method + simplSchema + jquery?

**Comment by AshHimself** [comment] 2018-04-10 05:34
All the validate of fields 'should' be done in validated-method + simplSchema. Jquery will only be used to update the DOM with the validation errors from the validated-method.

**Comment by AshHimself** [comment] 2018-04-10 05:35
@blockrazorbot claim

**Comment by gazhayes** [comment] 2018-04-10 05:35
Yep cool that's the simplest solution I believe.

**Comment by AshHimself** [comment] 2018-04-11 08:29
@anbud  @janat08 - For validating the attributes in saveCoin can I reuse the schema that was aready defined by @janat08 ? Something like the below. The Currencies namespace is currently not available and when I do import it I get a duplicate declaration error. Thought i'd just reach for help before burning too many hours on this. 

> export const addCurrency = new ValidatedMethod({
>     name: 'addCurrency',
>     //Define the validation rules which will be applied on both the client and server
>     validate: Currencies.schema,
>     run({ currencyId,url,image }) {
>       //Define the body of the ValidatedMethod, e.g. insert some data to a collection
>         if (Meteor.userId()) {
>           //DO THE ADD COIN STUFF HERE
> 
>         } else {
>             throw new Meteor.Error('Error.', 'You have to be logged in.')
>         }
>     }
> })
>

**Comment by AshHimself** [comment] 2018-04-12 02:43
@janat08 yep I tried to use 'Currencies.schema' as the schema in the validated-method per the above code but getting the following error. I assume this is something simple i'm missing and I agree the simple schema could do with a little update to make it more elegant and scalable. 

`TypeError: Currencies.schema is not a function
    at methods.js (imports/api/coins/methods.js:17:26)
    at fileEvaluate (packages/modules-runtime.js:343:9)
    at require (packages/modules-runtime.js:238:16)
    at index.js (imports/startup/both/index.js:1:152)
    at fileEvaluate (packages/modules-runtime.js:343:9)
    at require (packages/modules-runtime.js:238:16)
    at index.js (imports/startup/server/index.js:1:14)
    at fileEvaluate (packages/modules-runtime.js:343:9)
    at require (packages/modules-runtime.js:238:16)
    at main.js (server/main.js:1:655)
Exited with code: 1
Your application is crashing. Waiting for file change.`

**Comment by gazhayes** [comment] 2018-04-12 06:37
ping @anbud

**Comment by janat08** [comment] 2018-04-12 07:48
#1083, btw you have to run validator() to return function that validated method can use.

**Comment by janat08** [comment] 2018-04-14 12:59
says here exchanges field is an object, it's an array in dump and isn't converted before insertion.

also there's conditional check that intends to ``If the coin exists, no matter what it is`` yet decided to run a check if ``altcoin && proposal`` then validating genesisTimestamp field to be inserted as intendedLaunch.

**Comment by gazhayes** [comment] 2018-04-14 13:09
> exchanges field is an object, it's an array in dump and isn't converted before insertion.

You can change the data type, it's no problem. I'm going to remove it from the add currency page anyway.

The second part you mentioned is to determine if the currency/project is already existing or if it is intended to launch in the future. This part is intentional. It could be an altcoin that is already launched, or an altcoin that is planned to launch, or an ICO that has already launched, or an ICO that is planned.

It could be messy (I wrote it quick and dirty) but it should all work correctly, as in you should be able to work out what the schema should look like based on the options. 

Another thing that could be done is to break up that add coin page into different pages depending on what type of currency/project it is, but since these are all to be used on / and filtered it's still better to keep them in the same collection.

**Comment by janat08** [comment] 2018-04-14 13:12
> exchanges field is an object
it didn't have a check for an array, and array is ``typeof`` object. we were going to add exchanges typeahead.

**Comment by gazhayes** [comment] 2018-04-14 13:16
Yep, I think you understand. You can do anything you want with that data type since it isn't really used anywhere yet, just do what you think makes the most sense.

**Comment by janat08** [comment] 2018-04-14 16:02
change max for numbers to 999 and the like, look to integrated addToInsert calls and insert object assignments, pass into custom functions validation error throws: https://github.com/aldeed/simple-schema-js#required, try and concatenate object containing functions (ab).

**Comment by gazhayes** [comment] 2018-04-18 10:24
@janat08 are you finished with this one?

**Comment by janat08** [comment] 2018-04-18 11:43
I'm almost done.

**Comment by gazhayes** [comment] 2018-04-18 12:00
No need to rush, I'm just catching up with the status.

**Comment by janat08** [comment] 2018-04-19 11:05
made reddit/official site/github/block explorer unrequired since in schema definitions they're both required and unrequired.

**Comment by gazhayes** [comment] 2018-04-19 11:08
They are required in some situations and not required in others, depending on the previous options selected on the form.

**Comment by gazhayes** [comment] 2018-04-19 11:09
For example block explorer is not required if the project is proposed but hasn't launched yet.

**Comment by janat08** [comment] 2018-04-19 14:56
I did some of those, some I left as comments, others I missed.

**Comment by gazhayes** [comment] 2018-04-19 15:00
OK. I had planned on properly thinking through and documenting the 'add coin' rules today so that this becomes much easier for you, but unfortunately I didn't get time. I'll hopefully get to that tomorrow.

**Comment by gazhayes** [comment] 2018-04-24 07:11
#1280 is related

**Comment by janat08** [comment] 2018-04-26 15:16
Quote from ui based issue.

OK, I think I've mostly worked this out.

It's probably easier to create a new route for this and keep the existing one as a reference till the new one works properly.

Wizard 1:
[Currency Name] [Symbol](min 2 max 5)
Verify both name and symbol are unique across pending and existing currencies.

Has this blockchain or currency already launched?
[YES, {{name}} has already launched] [NO, {{name}} is new and has not launched yet]

Was this created as a fork of an existing blockchain, or was it launched with a new genesis block?
[{{name}} is a fork of something else] [{{name}} started with a new genesis block]

(if FORK):
Which blockchain was {{name}} forked from?
[typeahead of existing currencies]

Were funds raised or tokens pre-sold prior to the launch of this blockchain project? Was this an ICO?
[NO TOKENS WERE PRE-SOLD]
[SOME TOKENS WERE PRE-SOLD]

The tense of all the above text should change based on whether or not the coin has launched or not.

The rest can basically follow as it currently works on the existing form but broken up into relevant pages or whatever.

There are some differences though:
There's now the possibility of selecting any existing coin as the parent blockchain. If this is the case, the genesis block timestamp should be taken straight from the parent currency and the user doesn't need to be asked. They do however need to be asked what date the fork happened on (when the chain split in two).

If this is or was an ICO: an independent ICO page should be added to collect relevant details, I'll add the details later in a new issue once this issue is closed, but basically the ability to add funding rounds etc.

**Comment by janat08** [comment] 2018-04-26 20:57
I imagine the people working on that issue will try and implement this outside simpleSchema, so close this if you like.

**Closed** 2018-04-27 01:15 UTC
Labels: in progress
