### ISSUE TITLE
problem: images are constantly reloading

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1886] opened 2018-09-11 07:28 UTC
Problem: images that don't exist (not found) are 'flashing' across the whole site and flooding the console with not found errors.

<img width="539" alt="screen shot 2018-09-11 at 3 24 29 pm" src="https://user-images.githubusercontent.com/8143945/45344855-4d0b9180-b5d7-11e8-81e9-77c6cfc00116.png">

**Comment by anbud** [comment] 2018-09-11 11:37
@emurgobot claim

**Comment by anbud** [comment] 2018-09-11 20:42
Fixed in #1890.

@emurgobot label "done"
@emurgobot remove "in progress"

**Comment by gazhayes** [comment] 2018-09-16 03:32
ping @anbud  This is still happening. There must be some nasty root cause.

https://youtu.be/amO75Ev_D_I

**Comment by anbud** [comment] 2018-09-16 06:57
I'll check it out, I've possibly fixed just one of the causes then. :)

**Closed** 2018-09-17 01:38 UTC
Labels: done
