### ISSUE TITLE
Problem: [/currency/x] pop-up about adding features invisible if window is scrolled

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#890] opened 2018-04-02 14:37 UTC
Problem: On /currency/x pop-up asking to add features for new currency doesn't appear in viewport if you scrolled down. It has transition animation which might be preventing it from appearing in the viewport, we have scroll magic library installed. The text shown in modal is- in features.html:
```
        <div class="modal-body">
          It looks like {{currencyName}} has only recently been added to Blockrazor and
          its features have not yet been added. This is a great opportunity for you to
          add one of {{currencyName}}'s features and earn some Krazor!
        </div>
```

**Comment by chamidu-supeshala** [comment] 2018-04-03 02:40
@janat08 Do you mean about helper modals? For me, those appears, but some part is behind the navbar. Is that the case?

**Comment by janat08** [comment] 2018-04-03 08:10
has the text like "this currency was recently added and as such it doesn't have enuf features."

**Comment by MadanBhandari** [comment] 2018-04-06 18:34
I didn't get this, how can I reproduce this problem ?

**Comment by janat08** [comment] 2018-04-06 23:11
if you search for quoted text above I'll imagine you'll find the template and relevant parts of code, if not ask  ashhimself as he's likely responsible.

**Comment by gazhayes** [comment] 2018-04-07 00:54
@MadanBhandari it's probably only on some screen sizes.

**Comment by gazhayes** [comment] 2018-04-07 01:01
@janat08 does the page go dark, but no modal appears?

**Comment by janat08** [comment] 2018-04-07 07:32
I actually saw a part of modal, don't remember about darkness.

**Comment by gazhayes** [comment] 2018-04-07 07:53
I can't reproduce, can you try to do it again and take a screen shot?

**Comment by janat08** [comment] 2018-04-07 11:34
``` currencyDetail/features.html
        <div class="modal-body">
          It looks like {{currencyName}} has only recently been added to Blockrazor and
          its features have not yet been added. This is a great opportunity for you to
          add one of {{currencyName}}'s features and earn some Krazor!
        </div>
```

**Comment by AshHimself** [comment] 2018-04-12 04:02
I am also unable to reproduce. I suggest closing and reopening again with repeatable replication steps and screenshot. @gazhayes

**Closed** 2018-04-12 04:10 UTC
