### ISSUE TITLE
Problem: [/] fast render doesn't work

### ISSUE THREAD

**Issue by janat08** [Blockrazor/blockrazor#1051] opened 2018-04-09 14:14 UTC
Problem: This subscription stops fast-render from working: https://github.com/Blockrazor/blockrazor/blob/1c0d76cbdb8b73b1a8fa03b98f906fdaec651030/imports/ui/pages/returnedCurrencies/returnedCurrencies.js#L35.
Allegedly [/problems/:id] also has the issue.

**Comment by gazhayes** [comment] 2018-04-11 06:25
Do you have any ideas for a solution?

**Comment by janat08** [comment] 2018-04-11 12:53
SubsCache is acting up, I'll do that one.

**Comment by janat08** [comment] 2018-04-11 15:18
@blockrazorbot claim

**Comment by janat08** [comment] 2018-04-11 15:39
This is what's preventing from fast-render working. I'll let someone else actually fix it. https://github.com/Blockrazor/blockrazor/blob/1c0d76cbdb8b73b1a8fa03b98f906fdaec651030/imports/ui/pages/returnedCurrencies/returnedCurrencies.js#L35

**Comment by janat08** [comment] 2018-04-11 15:40
@blockrazorbot unclaim

**Comment by anbud** [comment] 2018-04-12 09:48
@blockrazorbot claim

**Comment by anbud** [comment] 2018-04-12 11:03
Fixed on `/` in #1088, but I can't reproduce it on `/problem/x`.

@blockrazorbot label "done"

**Comment by janat08** [comment] 2018-04-12 15:44
So the solution is just to add {}, cuz it's breaking for me with trying to set limit on publication because I'm passing a param to publicaiton.

**Comment by janat08** [comment] 2018-04-13 17:03
Logged issue here: https://github.com/abecks/meteor-fast-render/issues/16

**Comment by gazhayes** [comment] 2018-04-14 01:06
@janat08 since the original issue is solved I'll close this. Please carefully document the problem you are having with passing params in a new issue.

**Closed by gazhayes** 2018-04-14 01:06 UTC
Labels: Paid-contributor Priority, done
