### ISSUE TITLE
Problem: [/currency/x] new exchanges not added to currency

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1320] opened 2018-04-27 01:09 UTC
Problem: when adding a new exchange on the currency detail page, the exchange is added to the list of available exchanges but it is not added to the currency itself. It also cannot be added to the currency through the typeahead until after a page refresh.

**Comment by janat08** [comment] 2018-04-27 12:38
Duplicate of https://github.com/Blockrazor/blockrazor/issues/1315

**Closed** 2018-04-27 12:58 UTC
