### ISSUE TITLE
Problem : App architecture introduces inefficiencies and overhead

### ISSUE THREAD

**Issue by Fen747** [Blockrazor/blockrazor#69] opened 2018-01-12 19:40 UTC
In its current state, the application architecture have many drawbacks, and implementing an architecture like the one recommended [here](http://www.meteor-tuts.com/chapters/3/structure.html).

Current drawbacks :

- bad separation of client side and server side code, resulting in potential future security leaks and bundle useless oversize
- hard to keep the separation of concerns and to implement a verbose, easy to document implementation of differents features
- code will be eagerly loaded even if it is not used
- the longer we wait before refactoring, the harder it will be.

New architecture benefits :

- clear module separation, MVC compliant
- efficient code-splitting, in order to reduce initial bundle size and improve app security
- every module is agnostic of other parts of the app, making it way easier to add or remove any future feature / module
- standardized folders orgaization, making the code modular & very easy to read

**Comment by anbud** [comment] 2018-01-25 12:03
@gazhayes, 
Should I tackle this, or are we leaving it as is for now?
I do agree with @Fen747, there are issues with client/server separation, and it'll be harder to separate them as we progress, but refactoring is always a big job.

**Comment by gazhayes** [comment] 2018-01-25 12:17
How would you go about solving this?

**Comment by anbud** [comment] 2018-01-26 12:20
Before Meteor 1.3, the current architecture was quite optimal. 
The biggest problem here is that Meteor loads all files outside of `imports` directory eagerly, which creates unnecessarily big bundles and degrades performance. So, that's why they decided to offer a possible solution to this problem by including ES2015 modules support in Meteor. 
Now, the recommended structure would be something like [this](http://www.meteor-tuts.com/chapters/3/structure.html) (explained [here](https://guide.meteor.com/structure.html)). The basic idea is to modularize the app, placing app's logic in the `imports` folder and importing things that are needed, both on client and server. It simply improves performance.
So, the work on this issue would be based around modularizing the current codebase as much as possible.

**Comment by gazhayes** [comment] 2018-02-07 20:40
Partial solution: all new features should use the imports structure https://guide.meteor.com/structure.html#example-app-structure

**Comment by gazhayes** [comment] 2018-03-08 20:10
@anbud have you started on this at all?

**Comment by gazhayes** [comment] 2018-03-08 22:01
Ok, since this will affect basically anyone working on any part of the codebase it's probably a good idea to send many smaller pull requests as you go rather than one big one at the end. Each module in a different pull requst maybe?

**Comment by anbud** [comment] 2018-03-08 22:39
Yap, that's exactly what I was thinking, each module in a different pull request is perfectly fine.

**Comment by gazhayes** [comment] 2018-03-08 23:05
@AshHimself @janat08 @MadanBhandari please keep an eye on this and keep your master branch in your fork up to date to avoid conflicts etc.

**Comment by MadanBhandari** [comment] 2018-03-09 05:53
I have already stared working on this, I will send PR by tonight.
Currently I am moving components (top & side navigation), layout (mainLayout) and home route to `/import`.

**Comment by janat08** [comment] 2018-03-09 08:45
doing rest of this

**Comment by janat08** [comment] 2018-03-09 11:03
This api was combined into folders (several collections within) users, hashing (as there was a massive method file for hashing already), miscellaneous for for graph/form data. I intend to keep ratings and elorankings combined. and combine walletImages with with wallet folder, and combine profileimages into users folder.

**Comment by gazhayes** [comment] 2018-03-09 11:16
There's also a lot of stuff from earlier on where I wrote the logic for multiple components/views/templates in one file.

Please break down your changes as much as possible and send multiple pull requests, one for each module would be good. Otherwise people working on other things are going to have a lot of conflicts.

**Comment by janat08** [comment] 2018-03-09 12:48
I'm talking about api where you'd try and bundle things into a thematic folder. The UI templates I'll decouple surely.

**Comment by MadanBhandari** [comment] 2018-03-09 13:02
@janat08 Can you please review my PR #398 ? Should I continue the same ?

**Comment by janat08** [comment] 2018-03-09 13:08
I'm not in love with template name of topNavNew. and meteor guide said to organize components by their routes, so I suppose the top nav and sidenav belong in layouts. Gazhayes asked me to do this, so I'll take it from here.

**Comment by MadanBhandari** [comment] 2018-03-09 13:16
That was supposed to be only topNav but I did not deleted or updated existing because that was breaking inner pages.

**Comment by janat08** [comment] 2018-03-09 14:07
I'll try to push changes ASAP, although entirely in small parts.

**Comment by janat08** [comment] 2018-03-10 09:25
All of collections are now available in /imports/api/indexDB.js as you may have noticed, which makes it easier to then move original collection declarations around and add collections into the file. It will also give you an overview of how API is grouped in folders.

**Comment by janat08** [comment] 2018-03-10 09:36
Here are my current notes/issues if weird stuff is happening and you're looking for some1 to blame, I'll post it when everything is moved into imports to solve then:

initializeuser might be a server only method, check it

sendMessage in imports in bounties/server/methods

ask some1 about the lib/Bounties as those functions are just left behind

exposed hashing methods to client

exposed rewards.js to client as utilities.js and server.js

developers and codebase in the same folder named developers

might have deleted stuff in moderator ui

**Comment by gazhayes** [comment] 2018-03-10 09:41
> initializeuser might be a server only method

Yeah that's server only, unless someone else has started using it client side for some reason.

> might have deleted stuff in moderator ui

Looks ok to me, but some things only show up in certain situations.

**Comment by gazhayes** [comment] 2018-03-10 09:41
> sendMessage in imports in bounties/server/methods

Where was it before?

**Comment by janat08** [comment] 2018-03-10 09:45
sendMessage is activityLog method, I think the issue was that is was just a exported function before which I switched to method.

**Comment by janat08** [comment] 2018-03-10 11:55
A lot of our logic is within the template that's rendered by router without any children and we have a lot of pages too, so I think we could try something other than what meteor guide suggests.

**Comment by gazhayes** [comment] 2018-03-10 11:56
How do you prefer to do it?

**Comment by janat08** [comment] 2018-03-10 14:43
Render by route/page with folder for it if there're children, with a folder for moderator pages.

**Comment by gazhayes** [comment] 2018-03-10 15:49
Yeah I think that's a good idea.

**Comment by janat08** [comment] 2018-03-11 07:50
initializeuser might be a server only method, check it

sendMessage in imports in bounties/server/methods was imported from activityLog as function which is not a method.

ask some1 about the lib/Bounties as those functions are just left behind, replicated as utilities.js in /api

exposed hashing methods to client

exposed rewards.js to client as utilities.js and server.js

developers and codebase in the same folder named developers

might have deleted stuff in moderator ui

/bounties/:_id route isn't done since it's broken

Outstanding issues.

**Comment by gazhayes** [comment] 2018-03-11 08:16
> /bounties/:_id route isn't done since it's broken

Are you fixing this?

**Comment by gazhayes** [comment] 2018-03-11 08:17
A few other things are broken too, e.g. compare currencies

**Comment by gazhayes** [comment] 2018-03-11 08:20
Actually, most of Blockrazor is now broken ;)

**Comment by AshHimself** [comment] 2018-03-11 08:38
yah I can confirm that most pages for me locally are not working.

**Comment by janat08** [comment] 2018-03-11 09:14
fixed in #475

**Comment by gazhayes** [comment] 2018-03-11 13:28
@janat08 what's the status of this one now?

**Comment by janat08** [comment] 2018-03-11 14:33
Well the server still has stuff in it that I dont know what happens in or afrad it split it.

I haven't taken a look at bounties/:id as I wasn't sure it's a real route.

The list of concerns above are just there, but otherwise, I'm not working on the issue.

**Comment by gazhayes** [comment] 2018-03-11 14:41
OK.

Can you do two things:

1. Can you carefully elaborate on *all* the problems you are currently unable to solve for this to make it complete, and then @anbud and myself will go through them all and work it out.

2. List anything (related to this issue) that you can fix and still want to work on (if there is anything).

That way, we will have a comprehensive idea of what's remaining to be done to close this issue.

**Comment by janat08** [comment] 2018-03-12 09:00
Looking to solve them before having elaborate on them.

- [x] initializeuser might be a server only method, check it


- [ ] /bounties/:_id route isn't done since it's broken, the route is broken (http://localhost:3000/bounties/TgRzdcBd4iy8GeYA) and tries to render templates that don't exist, and in fact conflicts with currencydetails route as it has the same route name. Delete it?
- [ ] sendMessage in imports in bounties/server/methods was imported from activityLog as function which is not a method.

- [ ] ask some1 about the lib/Bounties as those functions are just left behind, replicated as utilities.js in /api


- [ ] exposed hashing methods to client


- [ ] exposed rewards.js to client as utilities.js and server.js


- [ ] developers and codebase in the same folder named developers


- [ ] might have deleted stuff in moderator ui

**Comment by janat08** [comment] 2018-03-12 09:54
@gazhayes I'm done.

**Comment by janat08** [comment] 2018-03-20 10:29
The stylesheets and tests folders are anti-pattern. you're not suppose to have to juggle between two folders whatever you're working on.

**Comment by janat08** [comment] 2018-03-21 09:15
> sendMessage is activityLog method, I think the issue was that is was just a exported function before which I switched to method.

will look at converting this back to client.

**Closed** 2018-03-21 11:06 UTC
