### ISSUE TITLE
Problem: TypeError: Cannot read property 'params' of null

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1445] opened 2018-05-04 06:50 UTC
Problem: console error on /addcoin: `TypeError: Cannot read property 'params' of null`

Solution: work out the cause of the problem and then decide if it's worth solving it.

**Comment by janat08** [comment] 2018-05-04 11:30
@blockrazorbot claim.

**Comment by janat08** [comment] 2018-05-04 11:39
The issue is about it not being able to parse navigation history, ill look into disabled that middleware even if I already looked into it before concluding that it actually isn't suppose to be enabled.

**Comment by janat08** [comment] 2018-05-04 12:46
I don't think that the error does anything.

**Comment by janat08** [comment] 2018-05-04 14:35
It's not an error with typeahead template either, nx-framework itself is interacting with router history.

**Comment by janat08** [comment] 2018-05-04 15:03
https://github.com/nx-js/framework/issues/25
@blockrazorbot label "low_priority"

**Comment by janat08** [comment] 2018-05-10 10:54
@blockrazorbot label "unmet dependency". unclaim

**Comment by janat08** [comment] 2018-05-10 10:54
@blockrazorbot unclaim

**Comment by gazhayes** [comment] 2018-05-10 11:12
What's the dependency?

**Comment by janat08** [comment] 2018-05-11 11:14
nx-js/framework#25

**Comment by anbud** [comment] 2018-05-27 19:02
Closing this one in favor of #1629.

**Closed by anbud** 2018-05-27 19:02 UTC
Labels: low_priority, unmet dependency
